# Generated by Django 3.2 on 2021-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210511_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersim',
            name='user_id_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='usersim',
            name='user_id_sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sim', to='user.user'),
        ),
    ]
