# Generated by Django 3.2 on 2021-05-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210512_1917'),
        ('user', '0003_auto_20210512_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='comment',
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='浏览'),
        ),
        migrations.CreateModel(
            name='UserCommentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=128, verbose_name='评论')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
