# Generated by Django 3.2 on 2021-05-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210515_1711'),
        ('user', '0004_auto_20210512_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTagReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
