# Generated by Django 3.2 on 2021-05-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usertagreadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='read_num',
            field=models.FloatField(default=0, verbose_name='浏览量'),
        ),
        migrations.DeleteModel(
            name='UserTagReadLog',
        ),
    ]
