# Generated by Django 3.2 on 2021-05-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssim',
            name='news_id_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
        migrations.AlterField(
            model_name='newssim',
            name='news_id_sim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sim', to='news.news'),
        ),
    ]
