# Generated by Django 3.2 on 2021-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210512_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(default='news.jpg', upload_to='', verbose_name='配图'),
        ),
    ]
