# Generated by Django 3.2 on 2021-05-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.TextField(default='', verbose_name='标签内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='标题'),
        ),
    ]
